# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By:  pedrrodr < pedrrodr@student.42malaga.c    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/15 13:04:47 by  pedrrodr         #+#    #+#              #
#    Updated: 2025/04/23 15:06:51 by  pedrrodr        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = cc

CFLAGS = -Wall -Wextra -Werror -I../Headers

AR = ar

IS_FTS = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_atoi.c ft_tolower.c ft_toupper.c
MEM_FTS = ft_memset.c ft_memmove.c ft_bzero.c ft_memchr.c ft_memcmp.c ft_calloc.c ft_memcpy.c
STR_FTS = ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strnstr.c ft_strdup.c ft_substr.c
ADDITIONAL_FTS = ft_substr.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_strjoin.c
BONUS_FTS = ft_lstnew.c ft_lstadd_front.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

SRC = $(IS_FTS) $(MEM_FTS) $(STR_FTS) $(ADDITIONAL_FTS) $(BONUS_FTS)


OBJ = $(SRC:.c=.o)
BONUS_OBJ = $(BONUS_FTS:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(AR) rcs $(NAME) $(OBJ)

bonus: $(OBJ) $(BONUS_OBJ)
	$(AR) rcs $(NAME) $(OBJ) $(BONUS_OBJ)
	
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(BONUS_OBJ)
fclean: clean
	rm -f $(NAME)
re: fclean all